### ISSUE TITLE
실제 작성하며 발생한 문제점 & 개선점

### ISSUE THREAD

**Issue by byundojin** [gamultong/RFC-KR#4]
### PR 제목 설정 
제대로 논의되지 않아 임의로 처리하였습니다.
또한 제안하여 주신
```text
번역 작업
[RFC-{문서 번호}] {문서 제목}
그 외
[RFC-{문서 번호}] {세부 사항}
```
또한 다음과 같은 문제점이 예상됩니다.
- 일관성 저하 -> 기본적으로 RFC 문서 제목이 일관성을 가지지 않습니다. 또한 번역 작업이 한번에 이뤄지지 않는 경우 여러 PR의 제목이 동일하여 가독성이 저하 됩니다. RFC문서의 분량을 생각하면 충분히 일어날 수 있는 상황이며, RFC의 분량은 한명이 단기간에 처리하기 힘든 양 입니다.
- 제목 길이 -> 세부 사항을 title에 표기하게 된다면, 제목 길이가 너무 길어져 가독성이 저하 됩니다.

이에 대한 해결책 제시입니다.
- RFC 당 고유 PR ID 추가 
- RFC 번역 작업과 그 외 작업 형식 통일
- RFC 그 외 세부 사항의 특정 경우 제시
```text
[RFC-{문서 번호}] {섹션 번호 혹은 Abstract} - {작업 e.g. 번역/수정/삭제} <- 이 부분 같이
```

### RFC 문서 첫 시작
RFC문서의 ToC를 들어가기 전 Abstract와 같은 문서를 의미합니다.
임의로 Abstract란 이름을 사용하였지만, 이는 일관성을 해치게 됩니다.
더 좋은 의견이 있다면 제시해 주세요.

### RFC 원문 추가
이는 제안입니다. 영어 원문을 추가하여 번역으로 주지 못한 정보를 제공하고 싶습니다. 그러나 이는 가독성을 해칠 수 있기에 원문을 추가하는 형식이 필요하다 느껴집니다.

### 본문이 없는 섹션에 ToC 추가
본문이 없는 섹션 or 대단원에 ToC를 추가하는 것 입니다.
이는 문서에 Title만 보여주는 것 보다. 문서의 흐름을 해치지 않고 자연스럽게 다음 문서로 넘어 갈 수 있는 방법이라 생각합니다.

### 문서 작성 형식 제공
이는 재대로 논의된 적 없지만 그 무엇보다 중요한 사항입니다.
독자에게 정보를 주는 직접적인 부분인 만큼 최소한의 일관성이 있어야한다 생각됩니다.

현재는 제목 - 내용 형식입니다.

이는 심도있게 논의되어야 합니다.

**Comment by byundojin** [comment]
@onee-only 읽고 타당하다 생각되는 부분과 그의 대한 의견이 있으시다면 말씀해 주세요.

**Comment by onee-only** [comment]
> * 일관성 저하 -> 기본적으로 RFC 문서 제목이 일관성을 가지지 않습니다. 또한 번역 작업이 한번에 이뤄지지 않는 경우 여러 PR의 제목이 동일하여 가독성이 저하 됩니다. RFC문서의 분량을 생각하면 충분히 일어날 수 있는 상황이며, RFC의 분량은 한명이 단기간에 처리하기 힘든 양 입니다.

번역 작업이 한번에 이뤄지지 않는 경우를 생각하지 못했네요. 단기간에 번역이 완료되지 않을 것을 감안하여 Draft PR을 올려 점진적으로 번역 하는 방법을 제안했는데, 기존 PR 작성자가 더이상 번역 작업을 하지 못하는 상황이 생길 수 있을 것 같습니다. 이와 관련해서 아래에서 다시 이야기 드리겠습니다.

> * 제목 길이 -> 세부 사항을 title에 표기하게 된다면, 제목 길이가 너무 길어져 가독성이 저하 됩니다.
> 
> 이에 대한 해결책 제시입니다.
> 
> * RFC 당 고유 PR ID 추가

RFC 문서 당 고유한 ID를 생성하고 이후 같은 문서에 대한 기여는 그 ID를 사용하자는 의미이신 것 같은데, 
문서의 번호로 ID의 역할을 대신 할 수 있다고 생각합니다. 따라서 기존에 결정 되었던 `[RFC-{문서 번호}]` 형식을 그대로 사용하면 되지 않을까 싶습니다.

> * RFC 번역 작업과 그 외 작업 형식 통일

저는 해결책 중 두 번째 방법을 사용하는 것이 좋아 보입니다. 
문서에 대한 기여라면 어떤 형태의 PR이든 아래와 같은 형식을 사용하는 것이 어떨까 싶습니다.

```
[RFC-{문서 번호}] {작업 요약}
```

작업 요약은 한 줄을 넘어가지 않도록 최대한 간결하고 핵심만 갖춘 내용을 의미합니다.
위 방식을 사용하면 일관성과 가독성 모두 해치지 않을 것 같습니다.

예시)
번역
```
[RFC-1945] Hypertext Transfer Protocol -- HTTP/1.0 번역
```
부분 번역: 위에서 이야기 했듯이, 기존 PR 작성자가 더 번역하지 못하는 경우입니다. 이 경우에는 부분적인 번역이라는 것을 명시합니다.
```
[RFC-1945] Hypertext Transfer Protocol -- HTTP/1.0 번역 (1 ~ 3.2)
```
수정
```
[RFC-1945] 1.1 섹션 오역 수정
```

추가로 이 방식을 차용한다고 하면 커밋도 이와 같은 방식을 사용하는 게 좋을 것 같습니다.

아래는 기존 방식으로 @byundojin 님께서 올리신 PR의 커밋 히스토리입니다.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/ce7b37a0-e2ea-4a4b-95a7-f793664b68b0">

각 커밋 메시지가 간결하지만, 작업 사항을 한번에 알기 어렵다는 단점이 있습니다. 커밋 메시지도 PR과 같이 작업 요약을 헤더에 두고, 더 자세한 정보가 있다면 본문에 배치하는 방식으로 바꾸는 게 좋을 것 같습니다.


> * RFC 그 외 세부 사항의 특정 경우 제시
> 
> ```
> [RFC-{문서 번호}] {섹션 번호 혹은 Abstract} - {작업 e.g. 번역/수정/삭제} <- 이 부분 같이
> ```

이 부분은 제대로 이해하지 못했습니다. 더 자세히 설명 부탁 드려도 될까요?


> ### RFC 문서 첫 시작
> RFC문서의 ToC를 들어가기 전 Abstract와 같은 문서를 의미합니다. 임의로 Abstract란 이름을 사용하였지만, 이는 일관성을 해치게 됩니다. 더 좋은 의견이 있다면 제시해 주세요.

저는 Abstract도 괜찮다고 생각합니다. 어떤 부분에서 일관성을 해치게 되는지 자세히 설명 부탁드립니다.

> ### RFC 원문 추가
> 이는 제안입니다. 영어 원문을 추가하여 번역으로 주지 못한 정보를 제공하고 싶습니다. 그러나 이는 가독성을 해칠 수 있기에 원문을 추가하는 형식이 필요하다 느껴집니다. 

각 문단 혹은 청크마다 열고 닫을 수 있는 형태로 제공하면 어떨까 싶습니다. 독자는 필요할 때 원문을 펴서 읽을 수 있고, PR 리뷰어는 raw 형태로 볼 수 있을테니 대조가 쉬울 것 같습니다.

> ### 본문이 없는 섹션에 ToC 추가
> 본문이 없는 섹션 or 대단원에 ToC를 추가하는 것 입니다. 이는 문서에 Title만 보여주는 것 보다. 문서의 흐름을 해치지 않고 자연스럽게 다음 문서로 넘어 갈 수 있는 방법이라 생각합니다.

좋은 의견입니다. 한발 더 나가서 본문이 있는 경우에도 추가하는 게 어떨까요? 이 또한 문서의 흐름을 파악하는 데 도움이 될 것이라고 생각합니다.

> ### 문서 작성 형식 제공
> 이는 재대로 논의된 적 없지만 그 무엇보다 중요한 사항입니다. 독자에게 정보를 주는 직접적인 부분인 만큼 최소한의 일관성이 있어야한다 생각됩니다.
> 
> 현재는 제목 - 내용 형식입니다.
> 
> 이는 심도있게 논의되어야 합니다.

동의합니다. 따로 이슈를 생성하는 게 어떨까요?

**Comment by byundojin** [comment]
모바일로 작성 중 이라 나눠서 올리는 점 양해 부탁드립니다.

> RFC 당 고유 PR ID 추가

이 것이 의미하는 것은 RFC 문서가 아닌 PR을  뜻하는 것 이였습니다.
같은 RFC문서 당 이름이 중복되는 PR이 생기니 이를 PR ID를 추가하여 PR을 구분하자는 의견이였습니다.

**Comment by byundojin** [comment]
> RFC문서의 ToC를 들어가기 전 Abstract와 같은 문서를 의미합니다. 임의로 Abstract란 이름을 사용하였지만, 이는 일관성을 해치게 됩니다. 더 좋은 의견이 있다면 제시해 주세요.

ToC에 포함된 Content의 Title과 다른 형태를 뛰기에 일관성이 떨어진다 하였고, 이와 같은 문서를 총칭할 만한 Title의 대하여 의견을 구하였습니다.

하지만 지금 생각하여 보니 Abstract 그대로 사용하는 것도 나쁘지 않을 듯 하네요.

**Comment by byundojin** [comment]
> 좋은 의견입니다. 한발 더 나가서 본문이 있는 경우에도 추가하는 게 어떨까요? 이 또한 문서의 흐름을 파악하는 데 도움이 될 것이라고 생각합니다.

 추가적인 의견 감사합니다. 정말 좋은 생각이네요.

하지만 그렇다면 그에 대한 형식이 필요 할 것 같습니다.

문서 형식을 의논할만한 Issue 생성해 주시면 거기서 이어가는 것이 좋겠습니다.

**Comment by byundojin** [comment]
> 각 커밋 메시지가 간결하지만, 작업 사항을 한번에 알기 어렵다는 단점이 있습니다. 커밋 메시지도 PR과 같이 작업 요약을 헤더에 두고, 더 자세한 정보가 있다면 본문에 배치하는 방식으로 바꾸는 게 좋을 것 같습니다.

이 부분에서는 의견이 엇갈리는 것 같습니다.
저는 세부 사항을 감추고 미리 정의된 섹션으로 추상화 하는 것이 더 낫다고 생각하였습니다.

```
[RFC-{문서 번호}] {섹션 번호 혹은 Abstract} - {작업 e.g. 번역/수정/삭제} <- 이 부분 같이
```
이 부분 또한 같은 의미 입니다.

작업을 번역/수정/삭제 섹션으로 미리 지정하고 각각의 commit을 지정된 섹션으로 추상화 한 것 처럼 PR또한 이와 같은 추상화로 Title에 대한 명료함을 가져가는 것이 좋다 생각하여서 예시를 들었던 것 입니다. 허나 설명이 부실하였던 것 같습니다.

**Comment by byundojin** [comment]
```
[RFC-1945] Hypertext Transfer Protocol -- HTTP/1.0 번역 (1 ~ 3.2)
```
작업 구역 표시하는 것 정말 훌룡한 의견이라 생각합니다.

**Comment by byundojin** [comment]
> 각 문단 혹은 청크마다 열고 닫을 수 있는 형태로 제공하면 어떨까 싶습니다. 독자는 필요할 때 원문을 펴서 읽을 수 있고, PR 리뷰어는 raw 형태로 볼 수 있을테니 대조가 쉬울 것 같습니다.

좋습니다. 처음 문서를 열었을 경우 닫혀있는 형태로 제공되나요? 이 부분에 대하여 잘 몰라 질문합니다. 만일 닫혀있는 형태로 제공된다면 더 좋을 것 같습니다.

원문의 양이 클 경우 원문을 잘라서 맞추어 제공하는 것이 좋다 생각합니다.
저는 한 문단단위로 잘랐지만 이는 너무 과하였다 생각합니다.
이에 대한 논의도 문서 작성 형식 Issue에서 이어가는 것이 좋을 것 같습니다.

**Comment by onee-only** [comment]
> > 각 커밋 메시지가 간결하지만, 작업 사항을 한번에 알기 어렵다는 단점이 있습니다. 커밋 메시지도 PR과 같이 작업 요약을 헤더에 두고, 더 자세한 정보가 있다면 본문에 배치하는 방식으로 바꾸는 게 좋을 것 같습니다.
> 
> 이 부분에서는 의견이 엇갈리는 것 같습니다. 저는 세부 사항을 감추고 미리 정의된 섹션으로 추상화 하는 것이 더 낫다고 생각하였습니다.
> 
> ```
> [RFC-{문서 번호}] {섹션 번호 혹은 Abstract} - {작업 e.g. 번역/수정/삭제} <- 이 부분 같이
> ```
> 
> 이 부분 또한 같은 의미 입니다.
> 
> 작업을 번역/수정/삭제 섹션으로 미리 지정하고 각각의 commit을 지정된 섹션으로 추상화 한 것 처럼 PR또한 이와 같은 추상화로 Title에 대한 명료함을 가져가는 것이 좋다 생각하여서 예시를 들었던 것 입니다. 허나 설명이 부실하였던 것 같습니다.

위와 같이 추상화를 함으로써 생기는 장점이 어떤 것이라고 생각하시나요? 각 방식의 장단점을 비교해보며 어떤 방식을 선택 할지 결정 하는 게 좋을 것 같습니다.

우선 제 의견의 장점은 커밋 헤더만으로 어떤 작업인지 한 눈에 볼 수 있다는 것이라고 생각합니다.

**Comment by onee-only** [comment]
> 모바일로 작성 중 이라 나눠서 올리는 점 양해 부탁드립니다.
> 
> > RFC 당 고유 PR ID 추가
> 
> 이 것이 의미하는 것은 RFC 문서가 아닌 PR을 뜻하는 것 이였습니다. 같은 RFC문서 당 이름이 중복되는 PR이 생기니 이를 PR ID를 추가하여 PR을 구분하자는 의견이였습니다.

이 또한 GitHub의 PR 일련번호로 구분이 가능 한 것으로 알고 있습니다. 
저는 작업 구역 표시로 위 문제를 충분히 해결 가능하다고 생각하는데, 추가적인 의견 있으신가요?

**Comment by byundojin** [comment]
https://github.com/gamultong/RFC-KR/issues/4#issuecomment-2264589684
> 위와 같이 추상화를 함으로써 생기는 장점이 어떤 것이라고 생각하시나요? 

작업을 추상화하면 일관성을 얻을 수 있습니다. 세부 내용과 같은 부분은 형식이 너무나도 자유롭기에 헤더에서는 추상화하여 표현하고, 본문에서 세부적인 내용을 보길 원하였습니다.
또한 세부 내용은 형식이 자유롭다보니 개인간 style차이가 발생 할 수 있는 부분입니다. 헤더에 세부를 표현하면 작업에 파악이 수월해지지만, 불특정 다수가 같이 협업한다면 이야기가 달라질 수 있습니다.
이런 style차이를 억제하기위해 추상화를 하여 헤더 형식을 강제 할 수 있습니다.

**Comment by byundojin** [comment]
https://github.com/gamultong/RFC-KR/issues/4#issuecomment-2264595663
> 이 또한 GitHub의 PR 일련번호로 구분이 가능 한 것으로 알고 있습니다.
저는 작업 구역 표시로 위 문제를 충분히 해결 가능하다고 생각하는데, 추가적인 의견 있으신가요?

일련 번호로 구분 가능하다면, 상관 없을 것 같습니다.
다만 작업 구역 표시만으로는 어려운 부분이 있을 수 있습니다. 번역하기 난해한 문서는 역자에 따라 다양한 수정이 일어날 수 있고 이를 고려해야합니다.

**Comment by onee-only** [comment]
지금까지 나온 의견 두 가지를 조합해서 
```
[RFC-{문서 번호}] {작업 e.g. 번역/수정/삭제} - {세부사항 요약}
```
이렇게 PR 타이틀을 쓰는 건 어떨까요?

**Comment by onee-only** [comment]
미팅에서 결론 난 대로 진행 하겠습니다.

# PR 타이틀 포맷
```
[RFC-{문서 번호}] - {세부사항 요약}
```
기존에 논의 한 작업 레이블을 제목에 넣는 건은 GitHub에서 제공하는 label로 대체 하기로 결정하였습니다.

# 커밋 포맷
```
[RFC-{문서 번호}] {섹션 번호} - {세부사항 요약}

구체적인 세부사항(있다면)
```
