### ISSUE TITLE
번역 문서에 영어 원문 추가

### ISSUE THREAD

**Issue by onee-only** [gamultong/RFC-KR#5]
> 각 문단 혹은 청크마다 열고 닫을 수 있는 형태로 제공하면 어떨까 싶습니다. 독자는 필요할 때 원문을 펴서 읽을 수 있고, PR 리뷰어는 raw 형태로 볼 수 있을테니 대조가 쉬울 것 같습니다.

좋습니다. 처음 문서를 열었을 경우 닫혀있는 형태로 제공되나요? 이 부분에 대하여 잘 몰라 질문합니다. 만일 닫혀있는 형태로 제공된다면 더 좋을 것 같습니다.

원문의 양이 클 경우 원문을 잘라서 맞추어 제공하는 것이 좋다 생각합니다.
저는 한 문단단위로 잘랐지만 이는 너무 과하였다 생각합니다.
이에 대한 논의도 문서 작성 형식 Issue에서 이어가는 것이 좋을 것 같습니다.

_Originally posted by @byundojin in https://github.com/gamultong/RFC-KR/issues/4#issuecomment-2264452740_

**Comment by onee-only** [comment]
> 좋습니다. 처음 문서를 열었을 경우 닫혀있는 형태로 제공되나요? 이 부분에 대하여 잘 몰라 질문합니다. 만일 닫혀있는 형태로 제공된다면 더 좋을 것 같습니다.

[예시](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)에서는 기본적으로 닫혀 있는 것으로 보입니다.

**Comment by byundojin** [comment]
원문을 자르는 것은 어느 정도가 적당할까요? 저는 한 문단으로 자르긴 했습니다. 이는 너무 잦은 자르기일 수 있습니다. 너무 자주 자르게 된다면 이는 문단간 연결성을 해칠 수 있고 부자연스럽게 느껴질 수 있습니다. 
하지만 문단만큼 명료한 단위를 찾기 어렵습니다. 의견 있으시다면 얘기해 주세요.

**Comment by onee-only** [comment]
> 원문을 자르는 것은 어느 정도가 적당할까요? 저는 한 문단으로 자르긴 했습니다. 이는 너무 잦은 자르기일 수 있습니다. 너무 자주 자르게 된다면 이는 문단간 연결성을 해칠 수 있고 부자연스럽게 느껴질 수 있습니다. 하지만 문단만큼 명료한 단위를 찾기 어렵습니다. 의견 있으시다면 얘기해 주세요.

저는 문단 단위를 유지 해야 한다고 생각합니다.
한 청크에 들어갈 라인 수를 정의 해 놓고 그에 맞게 유동적으로 문단 단위로 넣으면 되지 않을까 싶습니다.

**Comment by byundojin** [comment]
https://github.com/gamultong/RFC-KR/pull/2/commits/1e62947ed7cfe4878725cfaade6bbc68939d1f0c

현재 작업 중인 문서입니다. 이와 같은 경우를 고려해야 합니다.

**Comment by onee-only** [comment]
> 한 청크에 들어갈 라인 수를 정의 해 놓고 그에 맞게 유동적으로 문단 단위로 넣으면 되지 않을까 싶습니다.

위에서 말씀하신 경우도 이와 같이 청크에 들어갈 라인(줄) 수를 정하고, 한 청크에 여러 개의 문단을 묶으면 될 것 같습니다.

**Comment by byundojin** [comment]
좋습니다. 나중에 layout 자동 생성을 논의 할 때 원문 또한 자동 생성하는 방안에 대해 논의해 보도록 하죠.
