### ISSUE TITLE
문서 형식 정의

### ISSUE THREAD

**Issue by onee-only** [gamultong/RFC-KR#6]
> 좋은 의견입니다. 한발 더 나가서 본문이 있는 경우에도 추가하는 게 어떨까요? 이 또한 문서의 흐름을 파악하는 데 도움이 될 것이라고 생각합니다.

 추가적인 의견 감사합니다. 정말 좋은 생각이네요.

하지만 그렇다면 그에 대한 형식이 필요 할 것 같습니다.

문서 형식을 의논할만한 Issue 생성해 주시면 거기서 이어가는 것이 좋겠습니다.

_Originally posted by @byundojin in https://github.com/gamultong/RFC-KR/issues/4#issuecomment-2264438919_

**Comment by byundojin** [comment]
저는 각 문서의 title은 소제목 정도의 크기로 나누어 표기하였습니다.
### 소제목

**Comment by byundojin** [comment]
또한 Title 밑에 해당 위치의 원문 link를 달았습니다.

**Comment by onee-only** [comment]
위 두 의견 모두 좋아 보입니다.

다음 페이지로 가는 링크는 어떻게 하는 게 좋을까요?

저는 문서 끝부분에 

[1.2 Example Title ->](.)

이런 방식으로 하는 것도 나쁘지 않아 보입니다.

**Comment by byundojin** [comment]
좋은 의견인 것 같습니다 :)

**Comment by byundojin** [comment]
- ToC 접기
- 이전, 다음 문서 링크
- 원문 링크
