### ISSUE TITLE
번역 정도 기준 정하기

### ISSUE THREAD

**Issue by onee-only** [gamultong/RFC-KR#7]
문서의 번역 정도를 정하고자 합니다.

의논하고자 하는 부분은 다음과 같습니다:

1. 직역과 의역 중 어느 것에 비중을 더 둘지
2. 단어 번역을 어떻게 할 것인지 (예: connection -> 커넥션 -> 연결)

이외에도 번역 기준 관련된 고민거리가 있으면 자유롭게 제시 해 주시기 바랍니다.

**Comment by byundojin** [comment]
저 또한 고민이 많이 되는 부분입니다.
> 직역과 의역 중 어느 것에 비중을 더 둘지

저는 의역에 비중을 두고 싶습니다. 영어 원문을 같이 표기하기로 한 이상 직역의 장점보단 의역의 장점이 더 두드러지게 나타날 것 같습니다.

> 단어 번역을 어떻게 할 것인지 (예: connection -> 커넥션 -> 연결)

저는 한국어로 대체 할 말이 없는 경우 영어로 표기하였습니다.
또한 IT와 밀접한 단어 또한 영어로 표기하였니다.

예시)
program 
이 단어는 한국어로 번역하여도 프로그램, 진행 순서, 계획 등 으로 번역할 수 있습니다.
하지만 IT업계에서 사용하는 program은 진행 순서, 계획과는 거리가 멀고,
프로그램은 그저 program을 한국어로 표기한 것 일 뿐 입니다.
이러한 특징을 가진 단어는 번역보다는 영어 그대로 표기하는 것이 좋다 생각합니다.

**Comment by onee-only** [comment]
저는 번역본에 영어 단어가 지나치게 많이 나오는 경우 가독성이 좋지 않아진다고 생각합니다.
그렇기 때문에 한국어로 대체 불가능한 단어가 아닌 이상 한국어로 읽을 수 있도록 해야 한다고 생각합니다. 

아래는 @byundojin 님께서 작성 해 주신 PR에서 발췌한 내용입니다. 영어 단어를 사용한 부분을 한국어로 발음을 표기 해 봤습니다.

원문
```
   The Hypertext Transfer Protocol (HTTP) is an application-level
   protocol with the lightness and speed necessary for distributed,
   collaborative, hypermedia information systems. HTTP has been in use
   by the World-Wide Web global information initiative since 1990. This
   specification reflects common usage of the protocol referred too as
   "HTTP/1.0". This specification describes the features that seem to be
   consistently implemented in most HTTP/1.0 clients and servers.
```

영어 포함
```
Hypertext Trensfer Protocol(HTTP)은 하이퍼미디어 시스템을 위해 고안된 가볍고 빠른 application-level의 protocol입니다. 
HTTP는 1990년의 global information initative인 World-Wide Web에 사용되었습니다. 
이 명세는 “HTTP/1.0”의 일반적인 사용을 반영합니다. 
이 명세는 cliet와 server에서 일관적으로 구현되는 HTTP/1.0의 기능을 설명합니다. 
```

영어 발음 한국어로 표기
```
Hypertext Trensfer Protocol(HTTP)은 하이퍼미디어 시스템을 위해 고안된 가볍고 빠른 어플리케이션 레벨의 프로토콜입니다. 
HTTP는 1990년의 global information initative인 World-Wide Web에 사용되었습니다. 
이 명세는 “HTTP/1.0”의 일반적인 사용을 반영합니다. 
이 명세는 클라이언트와 서버에서 일관적으로 구현되는 HTTP/1.0의 기능을 설명합니다. 
```

저는 후자에서 가독성이 더 증가했다고 생각합니다. 
도진님께서 위에서 말씀 하신 것처럼 영어 원문을 같이 제공하기 때문에 한국어로 표기된 단어와 영어 단어 매칭도 수월할 것으로 보입니다.

**Comment by byundojin** [comment]
비교하여 보니 후자가 더 가독성이 높게 느껴지네요.

저는 IT업계에서 다른 의미로 사용되는 단어들이 존재하기에 이를 원문 그대로 표기하는 것에 좋다 생각하였지만, 원문을 같이 제공하는 이상 번역하여 표기하는 것이 좋아보입니다.

> 단어 번역을 어떻게 할 것인지 (예: connection -> 커넥션 -> 연결)

그러나 `connection -> 연결` 로 번역하는 것은 오히려 혼란을 부를 수 있으니 IT업계에서 다른 의미로 사용하는 단어들은 발음만 한국어로 표기하는 것이 나을 것 같습니다.

또한 이는 문서마다 문맥이 다르니 예외적인 부분도 존재할 것이고,
이는 역자의 역량에 맡겨야 할 것 같습니다.

예)
https://github.com/gamultong/RFC-KR/pull/2/commits/1e62947ed7cfe4878725cfaade6bbc68939d1f0c
#### connection 
응용 프로그램들 사이에 통신을 목적으로 전송 계층에서 가상 회선을 구축한 상태

#### message
HTTP의 기본 통신 단위, Section 4에 정의된 형식에 맞추어 구조화된 8bit 데이터의 연속
connection을 통해 전송된다.

message를 설명할 때 위 설명된 connection임을 알리기 위해 똑같이 영어로 표기하였습니다.
